### ISSUE TITLE
how to make assets folder into dist folder

### ISSUE THREAD

**Issue by cloudshadow** [PatrickJS/NG6-starter#139]
I create assets folder under app and save some images in it.
but no image be moved into dist folder after i run 'gulp webpack' 
please help me.

**Comment by cloudshadow** [comment]
already add loader but still not work
{
        test: /\.(png|jpg|gif|svg|woff2?|eot|ttf)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: '[name].[ext]?[hash:7]'
        }
      }

**Comment by samithaf** [comment]
Maybe have a look on https://github.com/petehunt/webpack-howto

**Comment by jvalen** [comment]
My way to solve this situation is by `CopyWebpackPlugin`. It'll just copy the assets folder into **dist** by using the plugin in `webpack.dist.config.js`.

I have my assets folder in `/client/assets`. Then

```javascript
//webpack.dist.config.js

var CopyWebpackPlugin = require('copy-webpack-plugin');
...
config.plugins = config.plugins.concat([
  new CopyWebpackPlugin([
    { from: 'client/assets', to: 'assets' }
  ]),
...
]);
```

I hope it helps

**Comment by sabareeshkk** [comment]
My solution is using **image-webpack-loader**.
**npm install  image-webpack-loader --save-dev**
and all image files copied to dist/assets folder.
{
        test: /\.(jpe?g|png|gif|svg)$/i,
        loaders: [
          'file?hash=sha512&digest=hex&name=assets/img/[name].[ext]',
          'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false'
        ]
      }

**Comment by Ajaykumarkonda** [comment]
I am using imagemin: {
      dist: {
        files: [{
          expand: true,
          cwd: '<%= yeoman.app %>/images',
          src: '{,*/}*.{png,jpg,jpeg,gif}',
          dest: '<%= yeoman.dist %>/images'
        }]
      }
    }
it is coping images from app folder but i need to know how to copy images from public folder to dist folder

Can any one help on this issue
